### ISSUE TITLE
test in ubuntu: AttributeError: 'NoneType' object has no attribute '_handle'

### ISSUE THREAD

**Issue by Jiangshan00001** [Jiangshan00001/pyttsx4#12]
**Describe the bug**
error when in ubuntu, without espeak installed.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu

**Smartphone (please complete the following information):**

**Additional context**

blank/test1.py 
test_save_to_file start
^CTraceback (most recent call last):
  File "/home/codespace/.python/current/lib/python3.10/site-packages/pyttsx4/__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "/home/codespace/.python/current/lib/python3.10/weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/codespace/.python/current/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/codespace/.python/current/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/codespace/.vscode-remote/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/codespace/.vscode-remote/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/codespace/.vscode-remote/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/codespace/.vscode-remote/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/codespace/.vscode-remote/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/codespace/.vscode-remote/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/workspaces/codespaces-blank/test1.py", line 188, in <module>
    test_save_to_file()
  File "/workspaces/codespaces-blank/test1.py", line 13, in test_save_to_file
    engine = pyttsx4.init()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/pyttsx4/__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/pyttsx4/engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/pyttsx4/driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "/home/codespace/.python/current/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/codespace/.python/current/lib/python3.10/site-packages/pyttsx4/drivers/espeak.py", line 9, in <module>
    from . import _espeak, toUtf8, fromUtf8
  File "/home/codespace/.python/current/lib/python3.10/site-packages/pyttsx4/drivers/_espeak.py", line 101, in <module>
    Initialize = cfunc('espeak_Initialize', dll, c_int,
  File "/home/codespace/.python/current/lib/python3.10/site-packages/pyttsx4/drivers/_espeak.py", line 15, in cfunc
    return CFUNCTYPE(result, *atypes)((name, dll), tuple(aflags))
AttributeError: 'NoneType' object has no attribute '_handle'
^CTraceback (most recent call last):
  File "/home/codespace/.vscode-remote/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2282, in __wait_for_threads_to_finish
    self._wait_for_threads_to_finish_called_event.wait(timeout=timeout)
  File "/home/codespace/.python/current/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/home/codespace/.python/current/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt

**Comment by Jiangshan00001** [comment]
fixed
